[package]
name = "attribution-engine"
version = "0.1.0"
edition = "2024"

[dependencies]
coverage-parser = { path = "../coverage-parser" }
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
thiserror.workspace = true
fuse-rust = "0.4.0"
